### ISSUE TITLE
[개인과제 리뷰] - 최원장 튜터

### ISSUE THREAD

**Issue by wonee09** [r03181231/the-best-movie-collection#14]
## 프리티어 사용 
![image](https://github.com/r03181231/the-best-movie-collection/assets/62840864/817fea26-06c0-4b26-acd8-62774b9c513f)
prettierrc 사용 너무 좋습니다. 간혹 간과해서, 코드의 통일성을 놓치는 경우가 있는데 협업 시에 일관된 코드 작성을 위해 꼭 필요한 부분이라 생각해요. 굳잡!

## 모듈화 및 코드 분리
![image](https://github.com/r03181231/the-best-movie-collection/assets/62840864/7cb9abb3-4eef-4973-8eea-71b7d3f2da85)
각 기능별로 모듈화하여 파일을 분리한 점이 인상적이네요. 코드의 가독성과 유지보수성을 높여주는 좋은 습관입니다.

## 비동기 처리
![image](https://github.com/r03181231/the-best-movie-collection/assets/62840864/1250b2ce-0b37-4e7e-9923-fa82dfa96f1c)
async와 await를 사용하여 비동기 처리를 명확하게 하고 콜백 지옥을 피하는 모습이 아주 좋습니다. then ~ catch, async ~ await 등 다양한 문법적 요소를 활용해보는 좋은 습관을 가지고 계신 것 같아요!
다만, async ~ await와 then이 함께 쓰였어요. 중복된 로직만 개선해주면 좋겠네요!

## 유틸리티 및 재사용 가능한 컴포넌트
공통적으로 사용되는 값을 `values.js`에서 관리하고, `cards` 함수를 재사용하여 UI를 구성한 부분이 효율적이네요. 개발자는 늘 '효율화'를 생각해야하죠.

## CSS
CSS 클래스 네이밍 및 구조가 명확하여 스타일을 이해하고 수정하기가 쉽습니다. 또한 reset을 해주면서, 통일성도 부여했네요! 굳

## 유효성 검사
![image](https://github.com/r03181231/the-best-movie-collection/assets/62840864/f01cbd6e-59e4-426d-b805-eb2ce010af67)
입력값 처리에 유효성 검사를 추가하여 사용자의 잘못된 입력을 예방한 점 => 사용자 경험을 생각하는 좋은 접근입니다.

**Comment by HaeRhee** [comment]
피드백 반영했습니다! 감사합니다!!
